test:
  stage: test
  image: node:20
  script:
    - npm install
    - npm run-script download_jar
    - npm run-script package
  artifacts:
    expire_in: 1 week
    paths:
      - b-language-extension-*.vsix
  cache:
    paths:
      - node_modules
