default:
  image: node:20
  before_script:
    - npm install

test:
  stage: test
  script:
    - npm run-script download_jar
    - npm run-script package
  artifacts:
    expire_in: 1 week
    paths:
      - b-language-extension-*.vsix
  cache:
    paths:
      - node_modules

deploy:
  stage: deploy
  needs:
    - test
  script:
    - npm exec vsce -- publish --packagePath b-language-extension-*.vsix
  only:
    - release@general/stups/b_language_extension
